plateforme_animation_territoire:
    resource: "@PlateformeAnimationTerritoireBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation


