plateforme_animation_territoire:
    resource: "@PlateformeAnimationTerritoireBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
